### ISSUE TITLE
Homework Feedback

### ISSUE THREAD

**Issue by arun-instructor** [hmarkas/Responsive-Blog#1]
Hashaam,

Nice work! This is an interesting approach. Not sure if you meant to do it, but your container has a fixed width until it hits the media query. If you do this, your page won't respond to screen sizes until it snaps to the mobile view.

To make it even more responsive you can use this instead:

```css
.container{
  width:100%;
  max-width:1000px;
  margin-left:auto;
  margin-right:auto;
}
```

That will allow the layout to flex until the breakpoint.
